name: estuche-virtual

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: estuche-backend
    restart: unless-stopped
    env_file:
      - ./be/.env
    command: sh -c "pnpm prisma generate && pnpm dev"
    volumes:
      - ./be:/app
      - be_node_modules:/app/node_modules
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: estuche-frontend
    restart: unless-stopped
    command: pnpm dev --host 0.0.0.0
    volumes:
      - ./fe:/app
      - fe_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  be_node_modules:
  fe_node_modules: